// Code generated by protoc-gen-go. DO NOT EDIT.
// source: intercom.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// The client request message containing the image.
type ClientBroadcastReq struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Bytes                []byte   `protobuf:"bytes,2,opt,name=bytes,proto3" json:"bytes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClientBroadcastReq) Reset()         { *m = ClientBroadcastReq{} }
func (m *ClientBroadcastReq) String() string { return proto.CompactTextString(m) }
func (*ClientBroadcastReq) ProtoMessage()    {}
func (*ClientBroadcastReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_4b7dc4dbe05ff714, []int{0}
}

func (m *ClientBroadcastReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientBroadcastReq.Unmarshal(m, b)
}
func (m *ClientBroadcastReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientBroadcastReq.Marshal(b, m, deterministic)
}
func (m *ClientBroadcastReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientBroadcastReq.Merge(m, src)
}
func (m *ClientBroadcastReq) XXX_Size() int {
	return xxx_messageInfo_ClientBroadcastReq.Size(m)
}
func (m *ClientBroadcastReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientBroadcastReq.DiscardUnknown(m)
}

var xxx_messageInfo_ClientBroadcastReq proto.InternalMessageInfo

func (m *ClientBroadcastReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ClientBroadcastReq) GetBytes() []byte {
	if m != nil {
		return m.Bytes
	}
	return nil
}

// The server response message.
type ClientBroadcastResp struct {
	Status               uint32   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	BroadcastAccepted    bool     `protobuf:"varint,2,opt,name=broadcast_accepted,json=broadcastAccepted,proto3" json:"broadcast_accepted,omitempty"`
	Reason               string   `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClientBroadcastResp) Reset()         { *m = ClientBroadcastResp{} }
func (m *ClientBroadcastResp) String() string { return proto.CompactTextString(m) }
func (*ClientBroadcastResp) ProtoMessage()    {}
func (*ClientBroadcastResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_4b7dc4dbe05ff714, []int{1}
}

func (m *ClientBroadcastResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientBroadcastResp.Unmarshal(m, b)
}
func (m *ClientBroadcastResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientBroadcastResp.Marshal(b, m, deterministic)
}
func (m *ClientBroadcastResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientBroadcastResp.Merge(m, src)
}
func (m *ClientBroadcastResp) XXX_Size() int {
	return xxx_messageInfo_ClientBroadcastResp.Size(m)
}
func (m *ClientBroadcastResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientBroadcastResp.DiscardUnknown(m)
}

var xxx_messageInfo_ClientBroadcastResp proto.InternalMessageInfo

func (m *ClientBroadcastResp) GetStatus() uint32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *ClientBroadcastResp) GetBroadcastAccepted() bool {
	if m != nil {
		return m.BroadcastAccepted
	}
	return false
}

func (m *ClientBroadcastResp) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

// The response message containing the reply
type ServerBroadcastReq struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServerBroadcastReq) Reset()         { *m = ServerBroadcastReq{} }
func (m *ServerBroadcastReq) String() string { return proto.CompactTextString(m) }
func (*ServerBroadcastReq) ProtoMessage()    {}
func (*ServerBroadcastReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_4b7dc4dbe05ff714, []int{2}
}

func (m *ServerBroadcastReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerBroadcastReq.Unmarshal(m, b)
}
func (m *ServerBroadcastReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerBroadcastReq.Marshal(b, m, deterministic)
}
func (m *ServerBroadcastReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerBroadcastReq.Merge(m, src)
}
func (m *ServerBroadcastReq) XXX_Size() int {
	return xxx_messageInfo_ServerBroadcastReq.Size(m)
}
func (m *ServerBroadcastReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerBroadcastReq.DiscardUnknown(m)
}

var xxx_messageInfo_ServerBroadcastReq proto.InternalMessageInfo

func (m *ServerBroadcastReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// The response message containing the reply
type ServerBroadcastResp struct {
	Name                    string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	IsCurrentlyBroadcasting bool     `protobuf:"varint,2,opt,name=is_currently_broadcasting,json=isCurrentlyBroadcasting,proto3" json:"is_currently_broadcasting,omitempty"`
	Height                  int32    `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
	Width                   int32    `protobuf:"varint,4,opt,name=width,proto3" json:"width,omitempty"`
	Type                    int32    `protobuf:"varint,5,opt,name=type,proto3" json:"type,omitempty"`
	Bytes                   []byte   `protobuf:"bytes,6,opt,name=bytes,proto3" json:"bytes,omitempty"`
	XXX_NoUnkeyedLiteral    struct{} `json:"-"`
	XXX_unrecognized        []byte   `json:"-"`
	XXX_sizecache           int32    `json:"-"`
}

func (m *ServerBroadcastResp) Reset()         { *m = ServerBroadcastResp{} }
func (m *ServerBroadcastResp) String() string { return proto.CompactTextString(m) }
func (*ServerBroadcastResp) ProtoMessage()    {}
func (*ServerBroadcastResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_4b7dc4dbe05ff714, []int{3}
}

func (m *ServerBroadcastResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerBroadcastResp.Unmarshal(m, b)
}
func (m *ServerBroadcastResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerBroadcastResp.Marshal(b, m, deterministic)
}
func (m *ServerBroadcastResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerBroadcastResp.Merge(m, src)
}
func (m *ServerBroadcastResp) XXX_Size() int {
	return xxx_messageInfo_ServerBroadcastResp.Size(m)
}
func (m *ServerBroadcastResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerBroadcastResp.DiscardUnknown(m)
}

var xxx_messageInfo_ServerBroadcastResp proto.InternalMessageInfo

func (m *ServerBroadcastResp) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ServerBroadcastResp) GetIsCurrentlyBroadcasting() bool {
	if m != nil {
		return m.IsCurrentlyBroadcasting
	}
	return false
}

func (m *ServerBroadcastResp) GetHeight() int32 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *ServerBroadcastResp) GetWidth() int32 {
	if m != nil {
		return m.Width
	}
	return 0
}

func (m *ServerBroadcastResp) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *ServerBroadcastResp) GetBytes() []byte {
	if m != nil {
		return m.Bytes
	}
	return nil
}

func init() {
	proto.RegisterType((*ClientBroadcastReq)(nil), "ClientBroadcastReq")
	proto.RegisterType((*ClientBroadcastResp)(nil), "ClientBroadcastResp")
	proto.RegisterType((*ServerBroadcastReq)(nil), "ServerBroadcastReq")
	proto.RegisterType((*ServerBroadcastResp)(nil), "ServerBroadcastResp")
}

func init() { proto.RegisterFile("intercom.proto", fileDescriptor_4b7dc4dbe05ff714) }

var fileDescriptor_4b7dc4dbe05ff714 = []byte{
	// 312 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x52, 0xcd, 0x4e, 0xf3, 0x30,
	0x10, 0xfc, 0xfc, 0xd1, 0x94, 0xb2, 0xe2, 0x47, 0x38, 0x15, 0x84, 0x9e, 0xaa, 0x9c, 0x72, 0x21,
	0x42, 0x70, 0xe3, 0x80, 0x44, 0x7a, 0xe2, 0x6a, 0x6e, 0x5c, 0x2a, 0x37, 0x5d, 0xb5, 0x96, 0x5a,
	0x27, 0xd8, 0x5b, 0x50, 0x5e, 0x83, 0xf7, 0xe1, 0xdd, 0x50, 0x1c, 0xb7, 0x54, 0x4d, 0x24, 0x4e,
	0xd9, 0xd9, 0xd9, 0x8c, 0xc7, 0xb3, 0x86, 0x73, 0xa5, 0x09, 0x4d, 0x5e, 0xac, 0xd3, 0xd2, 0x14,
	0x54, 0xc4, 0x4f, 0xc0, 0x27, 0x2b, 0x85, 0x9a, 0x32, 0x53, 0xc8, 0x79, 0x2e, 0x2d, 0x09, 0x7c,
	0xe7, 0x1c, 0x7a, 0x5a, 0xae, 0x31, 0x62, 0x63, 0x96, 0x9c, 0x08, 0x57, 0xf3, 0x21, 0x04, 0xb3,
	0x8a, 0xd0, 0x46, 0xff, 0xc7, 0x2c, 0x39, 0x15, 0x0d, 0x88, 0x09, 0xc2, 0xd6, 0xff, 0xb6, 0xe4,
	0x57, 0xd0, 0xb7, 0x24, 0x69, 0x63, 0x9d, 0xc4, 0x99, 0xf0, 0x88, 0xdf, 0x02, 0x9f, 0x6d, 0x07,
	0xa7, 0x32, 0xcf, 0xb1, 0x24, 0x9c, 0x3b, 0xc5, 0x81, 0xb8, 0xdc, 0x31, 0xcf, 0x9e, 0xa8, 0x65,
	0x0c, 0x4a, 0x5b, 0xe8, 0xe8, 0xc8, 0x39, 0xf1, 0x28, 0x4e, 0x80, 0xbf, 0xa2, 0xf9, 0x40, 0xf3,
	0x97, 0xeb, 0xf8, 0x9b, 0x41, 0xd8, 0x1a, 0xb5, 0x65, 0xe7, 0x0d, 0x1f, 0xe1, 0x46, 0xd9, 0x69,
	0xbe, 0x31, 0x06, 0x35, 0xad, 0xaa, 0xe9, 0xce, 0x8f, 0xd2, 0x0b, 0xef, 0xf1, 0x5a, 0xd9, 0xc9,
	0x96, 0xcf, 0xf6, 0xe8, 0xda, 0xe9, 0x12, 0xd5, 0x62, 0x49, 0xce, 0x69, 0x20, 0x3c, 0xaa, 0x53,
	0xfb, 0x54, 0x73, 0x5a, 0x46, 0x3d, 0xd7, 0x6e, 0x40, 0x7d, 0x3a, 0x55, 0x25, 0x46, 0x81, 0x6b,
	0xba, 0xfa, 0x37, 0xdf, 0xfe, 0x5e, 0xbe, 0xf7, 0x5f, 0x0c, 0x06, 0x2f, 0x7e, 0x65, 0x3c, 0x83,
	0x8b, 0x83, 0xb0, 0x79, 0x98, 0xb6, 0xd7, 0x37, 0x1a, 0xa6, 0x1d, 0x3b, 0x89, 0xff, 0x25, 0xec,
	0x8e, 0xd5, 0x1a, 0x07, 0x79, 0xf0, 0x30, 0x6d, 0x87, 0x39, 0x1a, 0xa6, 0x1d, 0xb1, 0x35, 0x1a,
	0xd9, 0xf1, 0x5b, 0xe0, 0x5e, 0xcf, 0xac, 0xef, 0x3e, 0x0f, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff,
	0xed, 0x26, 0x6a, 0xd9, 0x56, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// IntercomClient is the client API for Intercom service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type IntercomClient interface {
	// Connect will hold the connection to the server
	ClientBroadcast(ctx context.Context, opts ...grpc.CallOption) (Intercom_ClientBroadcastClient, error)
	ServerBroadcast(ctx context.Context, opts ...grpc.CallOption) (Intercom_ServerBroadcastClient, error)
}

type intercomClient struct {
	cc *grpc.ClientConn
}

func NewIntercomClient(cc *grpc.ClientConn) IntercomClient {
	return &intercomClient{cc}
}

func (c *intercomClient) ClientBroadcast(ctx context.Context, opts ...grpc.CallOption) (Intercom_ClientBroadcastClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Intercom_serviceDesc.Streams[0], "/Intercom/ClientBroadcast", opts...)
	if err != nil {
		return nil, err
	}
	x := &intercomClientBroadcastClient{stream}
	return x, nil
}

type Intercom_ClientBroadcastClient interface {
	Send(*ClientBroadcastReq) error
	Recv() (*ClientBroadcastResp, error)
	grpc.ClientStream
}

type intercomClientBroadcastClient struct {
	grpc.ClientStream
}

func (x *intercomClientBroadcastClient) Send(m *ClientBroadcastReq) error {
	return x.ClientStream.SendMsg(m)
}

func (x *intercomClientBroadcastClient) Recv() (*ClientBroadcastResp, error) {
	m := new(ClientBroadcastResp)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *intercomClient) ServerBroadcast(ctx context.Context, opts ...grpc.CallOption) (Intercom_ServerBroadcastClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Intercom_serviceDesc.Streams[1], "/Intercom/ServerBroadcast", opts...)
	if err != nil {
		return nil, err
	}
	x := &intercomServerBroadcastClient{stream}
	return x, nil
}

type Intercom_ServerBroadcastClient interface {
	Send(*ServerBroadcastReq) error
	Recv() (*ServerBroadcastResp, error)
	grpc.ClientStream
}

type intercomServerBroadcastClient struct {
	grpc.ClientStream
}

func (x *intercomServerBroadcastClient) Send(m *ServerBroadcastReq) error {
	return x.ClientStream.SendMsg(m)
}

func (x *intercomServerBroadcastClient) Recv() (*ServerBroadcastResp, error) {
	m := new(ServerBroadcastResp)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// IntercomServer is the server API for Intercom service.
type IntercomServer interface {
	// Connect will hold the connection to the server
	ClientBroadcast(Intercom_ClientBroadcastServer) error
	ServerBroadcast(Intercom_ServerBroadcastServer) error
}

func RegisterIntercomServer(s *grpc.Server, srv IntercomServer) {
	s.RegisterService(&_Intercom_serviceDesc, srv)
}

func _Intercom_ClientBroadcast_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(IntercomServer).ClientBroadcast(&intercomClientBroadcastServer{stream})
}

type Intercom_ClientBroadcastServer interface {
	Send(*ClientBroadcastResp) error
	Recv() (*ClientBroadcastReq, error)
	grpc.ServerStream
}

type intercomClientBroadcastServer struct {
	grpc.ServerStream
}

func (x *intercomClientBroadcastServer) Send(m *ClientBroadcastResp) error {
	return x.ServerStream.SendMsg(m)
}

func (x *intercomClientBroadcastServer) Recv() (*ClientBroadcastReq, error) {
	m := new(ClientBroadcastReq)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Intercom_ServerBroadcast_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(IntercomServer).ServerBroadcast(&intercomServerBroadcastServer{stream})
}

type Intercom_ServerBroadcastServer interface {
	Send(*ServerBroadcastResp) error
	Recv() (*ServerBroadcastReq, error)
	grpc.ServerStream
}

type intercomServerBroadcastServer struct {
	grpc.ServerStream
}

func (x *intercomServerBroadcastServer) Send(m *ServerBroadcastResp) error {
	return x.ServerStream.SendMsg(m)
}

func (x *intercomServerBroadcastServer) Recv() (*ServerBroadcastReq, error) {
	m := new(ServerBroadcastReq)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Intercom_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Intercom",
	HandlerType: (*IntercomServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ClientBroadcast",
			Handler:       _Intercom_ClientBroadcast_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "ServerBroadcast",
			Handler:       _Intercom_ServerBroadcast_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "intercom.proto",
}
