// Code generated by protoc-gen-go. DO NOT EDIT.
// source: intercom.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// The request message containing the image.
type BroadcastReq struct {
	Text                 string   `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BroadcastReq) Reset()         { *m = BroadcastReq{} }
func (m *BroadcastReq) String() string { return proto.CompactTextString(m) }
func (*BroadcastReq) ProtoMessage()    {}
func (*BroadcastReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_4b7dc4dbe05ff714, []int{0}
}

func (m *BroadcastReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BroadcastReq.Unmarshal(m, b)
}
func (m *BroadcastReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BroadcastReq.Marshal(b, m, deterministic)
}
func (m *BroadcastReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BroadcastReq.Merge(m, src)
}
func (m *BroadcastReq) XXX_Size() int {
	return xxx_messageInfo_BroadcastReq.Size(m)
}
func (m *BroadcastReq) XXX_DiscardUnknown() {
	xxx_messageInfo_BroadcastReq.DiscardUnknown(m)
}

var xxx_messageInfo_BroadcastReq proto.InternalMessageInfo

func (m *BroadcastReq) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

// The response message containing the reply
type BroadcastResp struct {
	Text                 string   `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BroadcastResp) Reset()         { *m = BroadcastResp{} }
func (m *BroadcastResp) String() string { return proto.CompactTextString(m) }
func (*BroadcastResp) ProtoMessage()    {}
func (*BroadcastResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_4b7dc4dbe05ff714, []int{1}
}

func (m *BroadcastResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BroadcastResp.Unmarshal(m, b)
}
func (m *BroadcastResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BroadcastResp.Marshal(b, m, deterministic)
}
func (m *BroadcastResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BroadcastResp.Merge(m, src)
}
func (m *BroadcastResp) XXX_Size() int {
	return xxx_messageInfo_BroadcastResp.Size(m)
}
func (m *BroadcastResp) XXX_DiscardUnknown() {
	xxx_messageInfo_BroadcastResp.DiscardUnknown(m)
}

var xxx_messageInfo_BroadcastResp proto.InternalMessageInfo

func (m *BroadcastResp) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func init() {
	proto.RegisterType((*BroadcastReq)(nil), "BroadcastReq")
	proto.RegisterType((*BroadcastResp)(nil), "BroadcastResp")
}

func init() { proto.RegisterFile("intercom.proto", fileDescriptor_4b7dc4dbe05ff714) }

var fileDescriptor_4b7dc4dbe05ff714 = []byte{
	// 124 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcb, 0xcc, 0x2b, 0x49,
	0x2d, 0x4a, 0xce, 0xcf, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0x52, 0xe2, 0xe2, 0x71, 0x2a,
	0xca, 0x4f, 0x4c, 0x49, 0x4e, 0x2c, 0x2e, 0x09, 0x4a, 0x2d, 0x14, 0x12, 0xe2, 0x62, 0x29, 0x49,
	0xad, 0x28, 0x91, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x02, 0xb3, 0x95, 0x94, 0xb9, 0x78, 0x91,
	0xd4, 0x14, 0x17, 0x60, 0x53, 0x64, 0x64, 0xc3, 0xc5, 0xe1, 0x09, 0x35, 0x5a, 0xc8, 0x80, 0x8b,
	0x13, 0xae, 0x41, 0x88, 0x57, 0x0f, 0xd9, 0x02, 0x29, 0x3e, 0x3d, 0x14, 0xb3, 0x94, 0x18, 0x34,
	0x18, 0x0d, 0x18, 0x9d, 0xd8, 0xa3, 0x58, 0xc1, 0xee, 0x49, 0x62, 0x03, 0x53, 0xc6, 0x80, 0x00,
	0x00, 0x00, 0xff, 0xff, 0xb6, 0x03, 0x8e, 0x15, 0xa8, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// IntercomClient is the client API for Intercom service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type IntercomClient interface {
	// Broadcast will send a greeting
	Broadcast(ctx context.Context, opts ...grpc.CallOption) (Intercom_BroadcastClient, error)
}

type intercomClient struct {
	cc *grpc.ClientConn
}

func NewIntercomClient(cc *grpc.ClientConn) IntercomClient {
	return &intercomClient{cc}
}

func (c *intercomClient) Broadcast(ctx context.Context, opts ...grpc.CallOption) (Intercom_BroadcastClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Intercom_serviceDesc.Streams[0], "/Intercom/Broadcast", opts...)
	if err != nil {
		return nil, err
	}
	x := &intercomBroadcastClient{stream}
	return x, nil
}

type Intercom_BroadcastClient interface {
	Send(*BroadcastReq) error
	Recv() (*BroadcastResp, error)
	grpc.ClientStream
}

type intercomBroadcastClient struct {
	grpc.ClientStream
}

func (x *intercomBroadcastClient) Send(m *BroadcastReq) error {
	return x.ClientStream.SendMsg(m)
}

func (x *intercomBroadcastClient) Recv() (*BroadcastResp, error) {
	m := new(BroadcastResp)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// IntercomServer is the server API for Intercom service.
type IntercomServer interface {
	// Broadcast will send a greeting
	Broadcast(Intercom_BroadcastServer) error
}

// UnimplementedIntercomServer can be embedded to have forward compatible implementations.
type UnimplementedIntercomServer struct {
}

func (*UnimplementedIntercomServer) Broadcast(srv Intercom_BroadcastServer) error {
	return status.Errorf(codes.Unimplemented, "method Broadcast not implemented")
}

func RegisterIntercomServer(s *grpc.Server, srv IntercomServer) {
	s.RegisterService(&_Intercom_serviceDesc, srv)
}

func _Intercom_Broadcast_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(IntercomServer).Broadcast(&intercomBroadcastServer{stream})
}

type Intercom_BroadcastServer interface {
	Send(*BroadcastResp) error
	Recv() (*BroadcastReq, error)
	grpc.ServerStream
}

type intercomBroadcastServer struct {
	grpc.ServerStream
}

func (x *intercomBroadcastServer) Send(m *BroadcastResp) error {
	return x.ServerStream.SendMsg(m)
}

func (x *intercomBroadcastServer) Recv() (*BroadcastReq, error) {
	m := new(BroadcastReq)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Intercom_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Intercom",
	HandlerType: (*IntercomServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Broadcast",
			Handler:       _Intercom_Broadcast_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "intercom.proto",
}
